CREATE SCHEMA IF NOT EXISTS kauz AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS info AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS iszl AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS kvazar AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS oms AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS plan AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS settings AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS users AUTHORIZATION postgres;
